#cloud-config
password: ubuntu
chpasswd: { expire: False }
ssh_pwauth: True
apt:
  proxy: http://proxy-dmz.intel.com:911
  http_proxy: http://proxy-dmz.intel.com:911
  https_proxy: http://proxy-dmz.intel.com:912
write_files:
  - path: "/etc/environment"
    content: |
      auto_proxy=http://wpad.intel.com/wpad.dat |
      http_proxy=http://proxy-chain.intel.com:911/ |
      https_proxy=http://proxy-dmz.intel.com:912/ |
      ftp_proxy=http://proxy-chain.intel.com:911/ |
      socks_proxy=http://proxy-chain.intel.com:1080/ |
      no_proxy="127.0.0.1,.intel.com,10.0.0.0/8,192.168.0.0/16,localhost,.local,127.0.0.0/8,134.134.0.0/16,::1,sifederation.intel.com,intelcorp.wc1.kontiki.com" |
      HTTP_PROXY=http://proxy-chain.intel.com:911 |
      HTTPS_PROXY=http://proxy-dmz.intel.com:912 |
      FTP_PROXY=http://proxy-chain.intel.com:911 |
      SOCKS_PROXY=http://proxy-chain.intel.com:1080
    append: true
  - path: "ben_build.sh"
    content: |
      BASEDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" |
      BCCDIR="${BASEDIR}/bcc" |
      BUILDDIR="${BCCDIR}/build" |
       |
      # Deps |
      sudo apt-get update |
      sudo apt-get -y install zip bison build-essential cmake flex git libedit-dev \|
              libllvm6.0 llvm-6.0-dev libclang-6.0-dev python zlib1g-dev libelf-dev \|
              libfl-dev python3-setuptools liblzma-dev arping netperf iperf \|
              python3-venv pkg-config gcc-multilib |
       |
      # Create a Python environment and activate it |
      cd ${BASEDIR} |
      sudo rm -rf ${BASEDIR}/env |
      if [ ! -d ${BASEDIR}/env ]; then |
              python3 -m venv ${BASEDIR}/env |
      fi |
      source ${BASEDIR}/env/bin/activate |
      which python |
      pip install wheel |
       |
      # Clone |
      git clone https://github.com/iovisor/bcc.git ${BCCDIR} |
      cd ${BCCDIR} |
       |
      rm -rf ${BUILDDIR} |
      mkdir ${BUILDDIR} |
      cd ${BUILDDIR} |
       |
      # Make the project |
      cd ${BUILDDIR} |
      cmake -DPYTHON_CMD=python3 .. |
      cd ${BUILDDIR}/src/python |
      make |
      # sudo make install |
      cd bcc-python3 |
      which python3 |
      python3 setup.py install --prefix=${BASEDIR}/env |
       |
      # Deactivate the Python environment |
      deactivate |
       |
      # Install Clang 12, which is just new enough to compile the libbpf-tools |
      cd ${BASEDIR} |
      wget https://apt.llvm.org/llvm.sh |
      chmod +x llvm.sh |
      sudo ${BASEDIR}/llvm.sh 12 |
       |
      # Make the libbpf tools |
      cd ${BASEDIR}/bcc/libbpf-tools |
      CLANG=clang-12 LLVM_STRIP=llvm-strip-12 make
